### ISSUE TITLE
Add "Remove cinnamon pannel shadow" for extra compatibility with intel videosprite drivers

### ISSUE THREAD

**Issue by DamienNZ** [Odyseus/CinnamonTools#40]
Just a feature request.

Thanks to your efforts in enabling the option to remove shadows has made using the "Intel videosprite" sub option mpv less painless by removing the blue borders caused by shadows. I was wondering if its possible to do the same with panels? as the shadow of a sidepanel overlaps onto the video on ether side on duel a monitor setup and would be an excellent workaround for all HD4000+ users who suffer video stuttering with opengl

Cheers
Damien

**Comment by Odyseus** [comment]
Hello, @DamienNZ.

The tweak that you are talking about only handles the shadows drawn by the window manager (muffin). That's why the tweak doesn't affect applications with client side decorations either. So, it is not possible to handle the shadows on the panels.

But there is something that you could try. You could edit the Cinnamon theme that you are using to remove the shadows from the panels. You just have to edit the **cinnamon.css** file on your theme's folder (Example: /path/to/your/theme/cinnamon/cinnamon.css), look for the classes called **panel-top**, **panel-bottom**, **panel-left** and **panel-right**. Then you set an opacity of 0 (zero) for the **box-shadow** property color of those classes.

This is an example of the theme that I use:

The default shadow values for the panels are like this:

```css
.panel-top,
.panel-bottom {
    background-gradient-direction: vertical;
    background-gradient-start: rgb(246, 246, 246);
    background-gradient-end: rgb(206, 206, 206);
    box-shadow: 0px 0px 1px 1px rgba(40, 40, 40, 0.4);
}
```

If I change it to this (note the **0.4** changed to just **0**)...

```css
.panel-top,
.panel-bottom {
    background-gradient-direction: vertical;
    background-gradient-start: rgb(246, 246, 246);
    background-gradient-end: rgb(206, 206, 206);
    box-shadow: 0px 0px 1px 1px rgba(40, 40, 40, 0);
}
```

...i can get rid of the shadows on the panels.
